### ISSUE TITLE
cpe-build script: ToDo

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-misc#2]
- [ ] check type system hierarchy (see issue: "cpe-build-script: TS hierarchy")
- [ ] script should be able to load/save pipelines and their configuration
- [ ] change dependency writing so that bugfix versions are incorporated
- [ ] at least minimal modification of component settings in interactive mode
- [ ] already check in script if Maven, Java and UIMA are correctly set up and installed
- [ ] allow for multiple consumer
- [ ] basic gui for the script
- [ ] fix mstparser issue (see issue: "cpe-build-script: mstparser in cpe")

**Comment by khituras** [comment]
This has been replaced by https://github.com/JULIELab/jcore-pipeline-modules
